### ISSUE TITLE
Implementing benchmark for std random(C++11) bind

### ISSUE THREAD

**Issue by satoren** [satoren/lua_binding_benchmark#10]
Remain `sol`,`sol2`,`Selene`,`luacppinterface`
but so dificults.

**Comment by satoren** [comment]
Implemented but not worked. a6bb8bee1bcbc927abdb154ffdd903e646e55f35 and cb50e12e0f9e7725cc0ccb4b7dcc900e1cc23654

**Comment by ThePhD** [comment]
I can do `sol2`.

**Comment by satoren** [comment]
Thanks. Please do it.

**Comment by ThePhD** [comment]
So this is weird. The `pcall( udist.__call, udist, udist ) ~= false` check is failing for `sol2`. Sol properly errors during that call, but instead of returning to `pcall` after `luaL_error`, it instead calls the panic function and then aborts. I'm not sure... why it's behaving like this. I'll have to check a few more things.

**Comment by satoren** [comment]
Maybe panic message is 'no error checked'
It's this
`if(pcall(udist.__call,udist,udist) ~= false)then error('no error checked') end\n`

**Comment by ThePhD** [comment]
Thanks for making this benchmark / test, helped me find a weakness in the sol2 code. It shooould work now! For both sol and sol2 (EDIT: aaahhh the original sol code makes me so sad I can't make it work proper).

**Comment by ThePhD** [comment]
Also, as a side note... `Sol2` is essentially the next iteration of `Sol`. The original library is never going to be updated (as far as from the original author's indications). It might be worth it to remove it from the benchmarks, since it's essentially entirely overridden by `Sol2`.

**Comment by satoren** [comment]
All done. thanks.
